version: 2.1

# Define jobs
jobs:
  # Job to install dependencies and run tests
  
  build-docker:
    docker:
      - image: circleci/node:18  # Use a Node.js Docker image
    steps:
      - checkout  # Check out the code from your Git repository

      - setup_remote_docker:
          version: 20.10.7  # Required if building Docker images

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Docker image
          command: docker build -t your-dockerhub-username/express-app:${CIRCLE_SHA1} .

      - run:
          name: Docker login
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - run:
          name: Push Docker image
          command: docker push your-dockerhub-username/express-app:${CIRCLE_SHA1}

# Define workflows to run jobs
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-docker
