version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:16.16  # Node.js image (you can change the version as needed)
    working_directory: ~/repo

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout  # Pulls the source code
      
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io
      
      - run:
          name: Set up Docker
          command: |
            sudo docker version 
      - run:
          name: Build Docker image
          command: |
            sudo docker build -t suriyashanmugam/ccon-dev-build:latest .
      
      - run:
          name: Push Docker image
          command: |
            sudo docker push suriyashanmugam/ccon-dev-build:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
