version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:14
    executor: node-executor
    steps:
      - checkout  # Check out the source code
      - run:
          name: Install dependencies
          command: |
            npm install --save

workflows:
  test_and_deploy:
    jobs:
      - build_test
